import { Client } from "../types/client";

export const dummyClients: Client[] = [
    {
        id: 1,
        name: "John Doe",
        email: "clienta@example.com",
        avatar: "https://randomuser.me/api/portraits/men/32.jpg",
        gender: "male",
        age: 32,
        tag: "VIP",
        notes: "Enjoys strong pressure massage, allergic to lavender oil.",
        remindersEnabled: true,
        preferences: {
            massageType: "Swedish Massage",
            pressureLevel: "Strong",
            oilAllergies: ["Lavender", "Eucalyptus"],
            roomTemperature: "Warm (24°C)",
            musicPreference: "Classical Piano",
            sessionDuration: "90 minutes",
        },
        appointmentHistory: [
            {
                id: 1,
                date: "2024-11-10T10:00:00Z",
                startTime: "10:00",
                endTime: "11:00",
                status: "Completed",
                location: "Room 1",
                createdAt: "2024-11-10T09:00:00Z",
                updatedAt: "2024-11-10T09:00:00Z",
                providerId: 1,
                clientId: 1,
                serviceType: "Deep Tissue",
                notes: "",
                metadata: {
                    providerName: "Masseur A",
                    clientName: "John Doe",
                },
            },
            {
                id: 2,
                date: "2025-02-12T14:00:00Z",
                startTime: "14:00",
                endTime: "15:00",
                status: "Upcoming",
                location: "Room 2",
                createdAt: "2025-02-01T09:00:00Z",
                updatedAt: "2025-02-01T09:00:00Z",
                providerId: 2,
                clientId: 1,
                serviceType: "Swedish Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur B",
                    clientName: "John Doe",
                },
            },
            {
                id: 3,
                date: "2025-02-15T14:00:00Z",
                startTime: "14:00",
                endTime: "15:00",
                status: "Upcoming",
                location: "Room 1",
                createdAt: "2025-02-01T09:00:00Z",
                updatedAt: "2025-02-01T09:00:00Z",
                providerId: 1,
                clientId: 1,
                serviceType: "Swedish Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur A",
                    clientName: "John Doe",
                },
            },
        ],
        messages: [
            {
                sender: "Staff",
                content: "Reminder: Your appointment is scheduled for Dec 1.",
                timestamp: "2024-11-30 10:00 AM",
            },
            {
                sender: "Client",
                content: "Thanks! I'll be there.",
                timestamp: "2024-11-30 10:15 AM",
            },
        ],
        feedback: [
            { rating: 5, comment: "Great experience!", date: "2024-11-11" },
            {
                rating: 4,
                comment: "Very relaxing, but room was a bit cold.",
                date: "2024-12-02",
            },
        ],
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 2,
        name: "Becky Davies",
        email: "clientb@example.com",
        avatar: "https://randomuser.me/api/portraits/women/32.jpg",
        gender: "female",
        age: 29,
        tag: "New",
        notes: "Mild back pain, recommended Deep Tissue.",
        remindersEnabled: false,
        preferences: {
            massageType: "Deep Tissue",
            pressureLevel: "Medium",
            roomTemperature: "Cool (21°C)",
            musicPreference: "Nature Sounds",
            sessionDuration: "60 minutes",
        },
        appointmentHistory: [
            {
                id: 4,
                date: "2025-02-10T09:00:00Z",
                startTime: "09:00",
                endTime: "10:00",
                status: "Upcoming",
                location: "Room 3",
                createdAt: "2025-02-01T09:00:00Z",
                updatedAt: "2025-02-01T09:00:00Z",
                providerId: 3,
                clientId: 2,
                serviceType: "First-time Consultation",
                notes: "",
                metadata: {
                    providerName: "Masseur C",
                    clientName: "Becky Davies",
                },
            },
        ],
        messages: [],
        feedback: [
            {
                rating: 3,
                comment: "Good but expected more relaxation.",
                date: "2025-02-01",
            },
        ],
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 3,
        name: "Michael Zhang",
        email: "clientc@example.com",
        avatar: "https://randomuser.me/api/portraits/men/31.jpg",
        gender: "male",
        age: 33,
        tag: "Frequent",
        notes: "Mild back pain, prefers firm pressure.",
        remindersEnabled: false,
        preferences: {
            massageType: "Sports Massage",
            pressureLevel: "Soft",
            roomTemperature: "Neutral (22°C)",
            musicPreference: "None",
            sessionDuration: "45 minutes",
        },
        appointmentHistory: [
            {
                id: 5,
                date: "2023-05-01T11:00:00Z",
                startTime: "11:00",
                endTime: "12:00",
                status: "Completed",
                location: "Room 2",
                createdAt: "2023-05-01T10:00:00Z",
                updatedAt: "2023-05-01T10:00:00Z",
                providerId: 4,
                clientId: 3,
                serviceType: "Deep Tissue",
                notes: "",
                metadata: {
                    providerName: "Masseur D",
                    clientName: "Michael Zhang",
                },
            },
            {
                id: 6,
                date: "2023-06-15T17:00:00Z",
                startTime: "17:00",
                endTime: "18:00",
                status: "Completed",
                location: "Room 2",
                createdAt: "2023-06-15T16:00:00Z",
                updatedAt: "2023-06-15T16:00:00Z",
                providerId: 4,
                clientId: 3,
                serviceType: "Sports Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur D",
                    clientName: "Michael Zhang",
                },
            },
        ],
        messages: [],
        feedback: [
            {
                rating: 2,
                comment: "Massage was too soft for my preference.",
                date: "2023-06-16",
            },
        ],
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 4,
        name: "Sarah Thompson",
        email: "clientd@example.com",
        avatar: "https://randomuser.me/api/portraits/women/33.jpg",
        gender: "female",
        age: 32,
        tag: "VIP",
        notes: "Loves aromatherapy massages.",
        remindersEnabled: true,
        preferences: {
            massageType: "Aromatherapy",
            pressureLevel: "Soft",
            roomTemperature: "Warm (25°C)",
            musicPreference: "Spa Ambience",
            sessionDuration: "60 minutes",
        },
        appointmentHistory: [
            {
                id: 7,
                date: "2024-12-02T15:00:00Z",
                startTime: "15:00",
                endTime: "16:00",
                status: "Upcoming",
                location: "Room 1",
                createdAt: "2024-11-30T10:00:00Z",
                updatedAt: "2024-11-30T10:00:00Z",
                providerId: 1,
                clientId: 4,
                serviceType: "Aromatherapy",
                notes: "",
                metadata: {
                    providerName: "Masseur A",
                    clientName: "Sarah Thompson",
                },
            },
        ],
        messages: [],
        feedback: [
            {
                rating: 5,
                comment: "Best massage ever!",
                date: "2024-10-10",
            },
        ],
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 5,
        name: "James Miller",
        email: "cliente@example.com",
        avatar: "https://randomuser.me/api/portraits/men/30.jpg",
        gender: "male",
        age: 23,
        tag: "Frequent",
        notes: "Loves strong pressure and long sessions.",
        remindersEnabled: true,
        preferences: {
            massageType: "Deep Tissue",
            pressureLevel: "Strong",
        },
        appointmentHistory: [
            {
                id: 8,
                date: "2025-02-12T14:00:00Z",
                startTime: "14:00",
                endTime: "15:00",
                status: "Upcoming",
                location: "Room 2",
                createdAt: "2025-01-01T10:00:00Z",
                updatedAt: "2025-01-01T10:00:00Z",
                providerId: 2,
                clientId: 5,
                serviceType: "Deep Tissue",
                notes: "",
                metadata: {
                    providerName: "Masseur B",
                    clientName: "James Miller",
                },
            },
            {
                id: 9,
                date: "2025-02-20T15:30:00Z",
                startTime: "15:30",
                endTime: "16:30",
                status: "Upcoming",
                location: "Room 3",
                createdAt: "2025-01-05T11:00:00Z",
                updatedAt: "2025-01-05T11:00:00Z",
                providerId: 3,
                clientId: 5,
                serviceType: "Hot Stone Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur C",
                    clientName: "James Miller",
                },
            },
            {
                id: 10,
                date: "2025-02-25T16:00:00Z",
                startTime: "16:00",
                endTime: "17:00",
                status: "Upcoming",
                location: "Room 4",
                createdAt: "2025-01-10T12:00:00Z",
                updatedAt: "2025-01-10T12:00:00Z",
                providerId: 4,
                clientId: 5,
                serviceType: "Thai Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur D",
                    clientName: "James Miller",
                },
            },
        ],
        messages: [],
        feedback: [
            {
                rating: 5,
                comment: "Excellent as always.",
                date: "2024-09-10",
            },
            {
                rating: 4,
                comment: "Would love stronger pressure next time.",
                date: "2024-10-12",
            },
        ],
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 6,
        name: "Lisa Ray",
        email: "clientf@example.com",
        avatar: "https://randomuser.me/api/portraits/women/34.jpg",
        gender: "female",
        age: 35,
        tag: "New",
        notes: "Enjoys lighter pressure.",
        remindersEnabled: false,
        preferences: {
            massageType: "Swedish Massage",
            pressureLevel: "Soft",
        },
        appointmentHistory: [
            {
                id: 11,
                date: "2024-09-05T16:30:00Z",
                startTime: "16:30",
                endTime: "17:30",
                status: "Completed",
                location: "Room 5",
                createdAt: "2024-09-05T15:30:00Z",
                updatedAt: "2024-09-05T15:30:00Z",
                providerId: 5,
                clientId: 6,
                serviceType: "Swedish Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur E",
                    clientName: "Lisa Ray",
                },
            },
        ],
        messages: [],
        feedback: [],
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 7,
        name: "David White",
        email: "clientg@example.com",
        avatar: "https://randomuser.me/api/portraits/men/29.jpg",
        gender: "male",
        age: 53,
        tag: "VIP",
        notes: "Prefers silent sessions, no small talk.",
        remindersEnabled: false,
        preferences: {
            massageType: "Hot Stone Massage",
            pressureLevel: "Medium",
        },
        appointmentHistory: [
            {
                id: 12,
                date: "2024-10-15T10:00:00Z",
                startTime: "10:00",
                endTime: "11:00",
                status: "Completed",
                location: "Room 6",
                createdAt: "2024-10-15T09:00:00Z",
                updatedAt: "2024-10-15T09:00:00Z",
                providerId: 6,
                clientId: 7,
                serviceType: "Hot Stone Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur F",
                    clientName: "David White",
                },
            },
        ],
        messages: [],
        feedback: [
            {
                rating: 5,
                comment: "Perfect session!",
                date: "2024-10-16",
            },
        ],
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 8,
        name: "Emily Johnson",
        email: "clienth@example.com",
        avatar: "https://randomuser.me/api/portraits/women/35.jpg",
        gender: "female",
        age: 42,
        tag: "VIP",
        notes: "Prefers a quiet, relaxing environment.",
        remindersEnabled: true,
        preferences: {
            massageType: "Hot Stone Massage",
            pressureLevel: "Soft",
        },
        appointmentHistory: [
            {
                id: 13,
                date: "2024-12-20T13:00:00Z",
                startTime: "13:00",
                endTime: "14:00",
                status: "Completed",
                location: "Room 7",
                createdAt: "2024-12-20T12:00:00Z",
                updatedAt: "2024-12-20T12:00:00Z",
                providerId: 7,
                clientId: 8,
                serviceType: "Hot Stone Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur G",
                    clientName: "Emily Johnson",
                },
            },
            {
                id: 14,
                date: "2025-01-10T14:00:00Z",
                startTime: "14:00",
                endTime: "15:00",
                status: "Upcoming",
                location: "Room 7",
                createdAt: "2025-01-05T10:00:00Z",
                updatedAt: "2025-01-05T10:00:00Z",
                providerId: 7,
                clientId: 8,
                serviceType: "Hot Stone Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur G",
                    clientName: "Emily Johnson",
                },
            },
        ],
        messages: [],
        feedback: [
            {
                rating: 5,
                comment: "Absolutely fantastic!",
                date: "2024-12-21",
            },
            {
                rating: 5,
                comment: "Best experience every time!",
                date: "2025-01-01",
            },
        ],
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 9,
        name: "Henry Adams",
        email: "clienti@example.com",
        avatar: "https://randomuser.me/api/portraits/men/28.jpg",
        gender: "male",
        age: 42,
        tag: "Frequent",
        notes: "Had a bad experience, needs a follow-up discussion.",
        remindersEnabled: false,
        preferences: {
            massageType: "Swedish Massage",
            pressureLevel: "Soft",
        },
        appointmentHistory: [
            {
                id: 15,
                date: "2024-09-15T10:00:00Z",
                startTime: "10:00",
                endTime: "11:00",
                status: "Completed",
                location: "Room 8",
                createdAt: "2024-09-15T09:00:00Z",
                updatedAt: "2024-09-15T09:00:00Z",
                providerId: 8,
                clientId: 9,
                serviceType: "Sports Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur H",
                    clientName: "Henry Adams",
                },
            },
            {
                id: 16,
                date: "2024-10-05T11:00:00Z",
                startTime: "11:00",
                endTime: "12:00",
                status: "Completed",
                location: "Room 9",
                createdAt: "2024-10-05T10:00:00Z",
                updatedAt: "2024-10-05T10:00:00Z",
                providerId: 9,
                clientId: 9,
                serviceType: "Swedish Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur I",
                    clientName: "Henry Adams",
                },
            },
        ],
        messages: [],
        feedback: [
            {
                rating: 1,
                comment: "Worst experience. Would not recommend.",
                date: "2024-10-06",
            },
            {
                rating: 2,
                comment: "Too much talking during the session.",
                date: "2024-09-16",
            },
        ],
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 10,
        name: "Olivia Spencer",
        email: "clientj@example.com",
        avatar: "https://randomuser.me/api/portraits/women/36.jpg",
        gender: "female",
        age: 21,
        tag: "VIP",
        notes: "No recent activity, should be re-engaged.",
        remindersEnabled: false,
        preferences: {
            massageType: "Swedish Massage",
            pressureLevel: "Medium",
        },
        appointmentHistory: [
            {
                id: 17,
                date: "2018-11-15T10:00:00Z",
                startTime: "10:00",
                endTime: "11:00",
                status: "Completed",
                location: "Room 10",
                createdAt: "2018-11-15T09:00:00Z",
                updatedAt: "2018-11-15T09:00:00Z",
                providerId: 10,
                clientId: 10,
                serviceType: "Aromatherapy",
                notes: "",
                metadata: {
                    providerName: "Masseur J",
                    clientName: "Olivia Spencer",
                },
            },
            {
                id: 18,
                date: "2019-08-20T16:00:00Z",
                startTime: "16:00",
                endTime: "17:00",
                status: "Completed",
                location: "Room 10",
                createdAt: "2019-08-20T15:00:00Z",
                updatedAt: "2019-08-20T15:00:00Z",
                providerId: 10,
                clientId: 10,
                serviceType: "Swedish Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur J",
                    clientName: "Olivia Spencer",
                },
            },
        ],
        messages: [],
        feedback: [],
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 11,
        name: "Daniel Kim",
        email: "clientk@example.com",
        avatar: "https://randomuser.me/api/portraits/men/27.jpg",
        gender: "male",
        age: 37,
        tag: "Frequent",
        notes: "Enjoys strong Thai Massage.",
        remindersEnabled: true,
        preferences: {
            massageType: "Thai Massage",
            pressureLevel: "Strong",
        },
        appointmentHistory: [
            {
                id: 19,
                date: "2025-02-10T09:00:00Z",
                startTime: "09:00",
                endTime: "10:00",
                status: "Upcoming",
                location: "Room 11",
                createdAt: "2025-02-01T08:00:00Z",
                updatedAt: "2025-02-01T08:00:00Z",
                providerId: 11,
                clientId: 11,
                serviceType: "Thai Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur K",
                    clientName: "Daniel Kim",
                },
            },
        ],
        messages: [],
        feedback: [],
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 12,
        name: "Sophia Lee",
        email: "clientl@example.com",
        avatar: "https://randomuser.me/api/portraits/women/37.jpg",
        gender: "female",
        age: 35,
        tag: "Frequent",
        notes: "Schedules multiple appointments in a short period.",
        remindersEnabled: true,
        preferences: {
            massageType: "Varied",
            pressureLevel: "Medium",
        },
        appointmentHistory: [
            {
                id: 20,
                date: "2025-02-12T14:00:00Z",
                startTime: "14:00",
                endTime: "15:00",
                status: "Upcoming",
                location: "Room 12",
                createdAt: "2025-01-05T10:00:00Z",
                updatedAt: "2025-01-05T10:00:00Z",
                providerId: 12,
                clientId: 12,
                serviceType: "Swedish Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur L",
                    clientName: "Sophia Lee",
                },
            },
            {
                id: 21,
                date: "2025-02-14T15:00:00Z",
                startTime: "15:00",
                endTime: "16:00",
                status: "Upcoming",
                location: "Room 12",
                createdAt: "2025-01-05T11:00:00Z",
                updatedAt: "2025-01-05T11:00:00Z",
                providerId: 12,
                clientId: 12,
                serviceType: "Hot Stone Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur L",
                    clientName: "Sophia Lee",
                },
            },
            {
                id: 22,
                date: "2025-02-16T16:00:00Z",
                startTime: "16:00",
                endTime: "17:00",
                status: "Upcoming",
                location: "Room 12",
                createdAt: "2025-01-05T12:00:00Z",
                updatedAt: "2025-01-05T12:00:00Z",
                providerId: 12,
                clientId: 12,
                serviceType: "Aromatherapy",
                notes: "",
                metadata: {
                    providerName: "Masseur L",
                    clientName: "Sophia Lee",
                },
            },
        ],
        messages: [],
        feedback: [
            {
                rating: 4,
                comment: "Always a good experience.",
                date: "2024-12-30",
            },
        ],
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 13,
        name: "Andrew Scott",
        email: "clientm@example.com",
        avatar: "https://randomuser.me/api/portraits/men/26.jpg",
        gender: "male",
        age: 45,
        tag: "New",
        notes: "Wants a massage, no extra engagement.",
        remindersEnabled: false,
        preferences: {
            massageType: "Deep Tissue",
            pressureLevel: "Strong",
        },
        appointmentHistory: [
            {
                id: 23,
                date: "2024-09-15T10:30:00Z",
                startTime: "10:30",
                endTime: "11:30",
                status: "Completed",
                location: "Room 13",
                createdAt: "2024-09-15T09:30:00Z",
                updatedAt: "2024-09-15T09:30:00Z",
                providerId: 13,
                clientId: 13,
                serviceType: "Deep Tissue",
                notes: "",
                metadata: {
                    providerName: "Masseur M",
                    clientName: "Andrew Scott",
                },
            },
        ],
        messages: [],
        feedback: [],
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 14,
        name: "Jessica Brown",
        email: "clientn@example.com",
        avatar: "https://randomuser.me/api/portraits/women/38.jpg",
        gender: "female",
        age: 70,
        tag: "Frequent",
        notes: "Loves detailed massages, always leaves feedback.",
        remindersEnabled: true,
        preferences: {
            massageType: "Hot Stone Massage",
            pressureLevel: "Soft",
        },
        appointmentHistory: [
            {
                id: 24,
                date: "2025-01-15T11:00:00Z",
                startTime: "11:00",
                endTime: "12:00",
                status: "Completed",
                location: "Room 14",
                createdAt: "2025-01-15T10:00:00Z",
                updatedAt: "2025-01-15T10:00:00Z",
                providerId: 14,
                clientId: 14,
                serviceType: "Hot Stone Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur N",
                    clientName: "Jessica Brown",
                },
            },
            {
                id: 25,
                date: "2025-01-15T11:00:00Z",
                startTime: "11:00",
                endTime: "12:00",
                status: "Completed",
                location: "Room 14",
                createdAt: "2025-01-15T10:00:00Z",
                updatedAt: "2025-01-15T10:00:00Z",
                providerId: 14,
                clientId: 14,
                serviceType: "Hot Stone Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur N",
                    clientName: "Jessica Brown",
                },
            },
            {
                id: 26,
                date: "2025-01-15T11:00:00Z",
                startTime: "11:00",
                endTime: "12:00",
                status: "Completed",
                location: "Room 14",
                createdAt: "2025-01-15T10:00:00Z",
                updatedAt: "2025-01-15T10:00:00Z",
                providerId: 14,
                clientId: 14,
                serviceType: "Hot Stone Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur N",
                    clientName: "Jessica Brown",
                },
            },
            {
                id: 27,
                date: "2025-01-15T11:00:00Z",
                startTime: "11:00",
                endTime: "12:00",
                status: "Completed",
                location: "Room 14",
                createdAt: "2025-01-15T10:00:00Z",
                updatedAt: "2025-01-15T10:00:00Z",
                providerId: 14,
                clientId: 14,
                serviceType: "Hot Stone Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur N",
                    clientName: "Jessica Brown",
                },
            },
            {
                id: 28,
                date: "2025-01-15T11:00:00Z",
                startTime: "11:00",
                endTime: "12:00",
                status: "Completed",
                location: "Room 14",
                createdAt: "2025-01-15T10:00:00Z",
                updatedAt: "2025-01-15T10:00:00Z",
                providerId: 14,
                clientId: 14,
                serviceType: "Hot Stone Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur N",
                    clientName: "Jessica Brown",
                },
            },
            {
                id: 29,
                date: "2025-01-15T11:00:00Z",
                startTime: "11:00",
                endTime: "12:00",
                status: "Completed",
                location: "Room 14",
                createdAt: "2025-01-15T10:00:00Z",
                updatedAt: "2025-01-15T10:00:00Z",
                providerId: 14,
                clientId: 14,
                serviceType: "Hot Stone Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur N",
                    clientName: "Jessica Brown",
                },
            },
            {
                id: 30,
                date: "2025-01-15T11:00:00Z",
                startTime: "11:00",
                endTime: "12:00",
                status: "Completed",
                location: "Room 14",
                createdAt: "2025-01-15T10:00:00Z",
                updatedAt: "2025-01-15T10:00:00Z",
                providerId: 14,
                clientId: 14,
                serviceType: "Hot Stone Massage",
                notes: "",
                metadata: {
                    providerName: "Masseur N",
                    clientName: "Jessica Brown",
                },
            },
        ],
        messages: [
            {
                sender: "Client",
                content:
                    "This was the most amazing session ever! I felt so relaxed afterward. Thank you for the effort!",
                timestamp: "2025-01-16 10:00 AM",
            },
        ],
        feedback: [
            {
                rating: 5,
                comment: "Incredible massage! I can't wait to come back.",
                date: "2025-01-16",
            },
        ],
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 15,
        name: "Sam Boltman",
        email: "clientm@example.com",
        avatar: "https://randomuser.me/api/portraits/men/45.jpg",
        gender: "male",
        age: 45,
        tag: "New",
        notes: "Wants a massage, no extra engagement.",
        remindersEnabled: false,
        preferences: {
            massageType: "Deep Tissue",
            pressureLevel: "Strong",
        },
        appointmentHistory: [
            {
                id: 31,
                date: "2024-09-15T10:30:00Z",
                startTime: "10:30",
                endTime: "11:30",
                status: "Completed",
                location: "Room 13",
                createdAt: "2024-09-15T09:30:00Z",
                updatedAt: "2024-09-15T09:30:00Z",
                providerId: 13,
                clientId: 15,
                serviceType: "Deep Tissue",
                notes: "",
                metadata: {
                    providerName: "Masseur M",
                    clientName: "Sam Boltman",
                },
            },
        ],
        messages: [],
        feedback: [],
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
];

export const tagColors = {
    VIP: "bg-yellow-500",
    Frequent: "bg-green-500",
    New: "bg-blue-500",
};

export const sortOptions = [
    { label: "Recent", value: "Last Appointment" },
    { label: "Name", value: "Name" },
    { label: "VIP Priority", value: "Frequency" },
] as const;
