# Harmonia Configuration File

# Server settings
Port: "3000"

# Database connection string (PostgreSQL in this example)
DatabaseURL: "user=postgres password=COMPUTERScience99@ dbname=harmonia sslmode=disable"

AuthProvider: "clerk"

# Authentication settings
ClerkPublicKeyURL: "https://api.clerk.dev/public-key" # Only used if AUTH_PROVIDER is "clerk"
ClerkSecretKey: "sk_test_X1nrGSq5xHvjhIusKfQA3J6v6QMIjTAm6XscRJKRL5"

# Payment settings
StripeSecretKey: "sk_test_yourStripeSecretKey"
PaymentAdapter: "stripe" # Options: "stripe", "paypal", etc.

# Calendar settings (using Google Calendar as default)
GoogleCredFile: "./path/to/credentials.json" # Path to your Google service account credentials file.
GoogleCalendarID: "your-google-calendar-id"

# Notification settings (using Twilio for SMS)
TwilioSID: "your-twilio-sid"
TwilioAuthToken: "your-twilio-auth-token"
TwilioFromPhone: "+1234567890"
