# Harmonia Configuration File

# Server settings
Port: "8080"

# Database connection string (PostgreSQL in this example)
DatabaseURL: "postgres://harmonia_user:secretpassword@localhost:5432/harmonia?sslmode=disable"

AuthProvider: "clerk"

# Authentication settings (using Auth0 by default)
AuthDomain: "dev-63lnnyvm5sp0cz2o.eu.auth0.com"
AuthAudience: "https://dev-63lnnyvm5sp0cz2o.eu.auth0.com/api/v2/"
AuthClientID: "E0CVtZtCGhPL0D8nUCLQmXnHZLBtwkSL"
AuthClientSecret: "Qz5XuFcwFiM6pJwsrzgKSS-Uj1kXtsnU2jXbeoO2x3okK6xZENFH4pHdUmTfItXr"
AuthCallbackURL: "https://reimagined-goggles-wgg96677x97c7q6-8080.app.github.dev/callback"

# Authentication settings
ClerkPublicKeyURL: "https://api.clerk.dev/public-key"  # Only used if AUTH_PROVIDER is "clerk"

# Payment settings
StripeSecretKey: "sk_test_yourStripeSecretKey"
PaymentAdapter: "stripe" # Options: "stripe", "paypal", etc.

# Calendar settings (using Google Calendar as default)
GoogleCredFile: "./path/to/credentials.json" # Path to your Google service account credentials file.
GoogleCalendarID: "your-google-calendar-id"

# Notification settings (using Twilio for SMS)
TwilioSID: "your-twilio-sid"
TwilioAuthToken: "your-twilio-auth-token"
TwilioFromPhone: "+1234567890"
