import { Client } from "../types/client";

export const dummyClients: Client[] = [
    {
        id: 1,
        name: "John Doe",
        email: "clienta@example.com",
        lastAppointment: "2024-12-31 14:00",
        details: "Regular client, prefers Swedish Massage.",
        avatar: "https://randomuser.me/api/portraits/men/32.jpg",
        tag: "VIP",
        notes: "Enjoys strong pressure massage, allergic to lavender oil.",
        appointmentHistory: [
            { date: "2024-11-10", type: "Deep Tissue", status: "Completed" },
            { date: "2025-02-12", type: "Swedish Massage", status: "Upcoming" },
            { date: "2025-02-15", type: "Swedish Massage", status: "Upcoming" },
        ],
        preferences: {
            massageType: "Swedish Massage",
            pressureLevel: "Strong",
            oilAllergies: ["Lavender", "Eucalyptus"],
            roomTemperature: "Warm (24°C)",
            musicPreference: "Classical Piano",
            sessionDuration: "90 minutes",
        },
        healthNotes: "Lower back pain, avoid excessive pressure in lumbar area.",
        mobilityIssues: "Mild stiffness in the left shoulder",
        remindersEnabled: true,
        staffNotes: [
            "Client prefers deep pressure on shoulders.",
            "Allergic to eucalyptus oil.",
            "Prefers warm towels before starting the session."
        ],
        previousMasseurNotes: [
            "Avoid too much pressure on the lower back.",
            "Likes soft kneading technique on neck and shoulders."
        ],
        messages: [
            { sender: "Staff", content: "Reminder: Your appointment is scheduled for Dec 1.", timestamp: "2024-11-30 10:00 AM" },
            { sender: "Client", content: "Thanks! I'll be there.", timestamp: "2024-11-30 10:15 AM" },
        ],
        feedback: [
            { rating: 5, comment: "Great experience!", date: "2024-11-11" },
            { rating: 4, comment: "Very relaxing, but room was a bit cold.", date: "2024-12-02" },
        ],
    },
    {
        id: 2,
        name: "Becky Davies",
        email: "clientb@example.com",
        lastAppointment: "2025-02-10 10:00",
        details: "First-time visitor, interested in Deep Tissue.",
        avatar: "https://randomuser.me/api/portraits/women/32.jpg",
        tag: "New",
        notes: "Mild back pain, recommended Deep Tissue.",
        appointmentHistory: [
            { date: new Date().toISOString().split("T")[0], type: "First-time Consultation", status: "Upcoming" }
        ],
        preferences: {
            massageType: "Deep Tissue",
            pressureLevel: "Medium",
            roomTemperature: "Cool (21°C)",
            musicPreference: "Nature Sounds",
            sessionDuration: "60 minutes",
        },
        healthNotes: "No major concerns.",
        remindersEnabled: false,
        staffNotes: ["Prefers light pressure, enjoys aromatherapy."],
        messages: [],
        feedback: [{ rating: 3, comment: "Good but expected more relaxation.", date: "2025-02-01" }],
    },
    {
        id: 3,
        name: "Michael Zhang",
        email: "clientc@example.com",
        lastAppointment: "2023-06-15 17:00",
        details: "Used to be a frequent client but hasn't visited in a long time.",
        avatar: "https://randomuser.me/api/portraits/men/31.jpg",
        tag: "Frequent",
        notes: "Mild back pain, prefers firm pressure.",
        appointmentHistory: [
            { date: "2023-05-01", type: "Deep Tissue", status: "Completed" },
            { date: "2023-06-15", type: "Sports Massage", status: "Completed" },
        ],
        preferences: {
            massageType: "Sports Massage",
            pressureLevel: "Soft",
            roomTemperature: "Neutral (22°C)",
            musicPreference: "None",
            sessionDuration: "45 minutes",
        },
        healthNotes: "Recurring tightness in hamstrings.",
        remindersEnabled: false,
        staffNotes: ["Client used to come regularly but hasn't visited recently."],
        messages: [],
        feedback: [
            { rating: 2, comment: "Massage was too soft for my preference.", date: "2023-06-16" },
        ],
    },
    {
        id: 4,
        name: "Sarah Thompson",
        email: "clientd@example.com",
        lastAppointment: "2024-12-02 15:00",
        details: "Regular client, coming today.",
        avatar: "https://randomuser.me/api/portraits/women/33.jpg",
        tag: "VIP",
        notes: "Loves aromatherapy massages.",
        appointmentHistory: [
            { date: "2024-12-02", type: "Aromatherapy", status: "Upcoming" },
        ],
        preferences: {
            massageType: "Aromatherapy",
            pressureLevel: "Soft",
            roomTemperature: "Warm (25°C)",
            musicPreference: "Spa Ambience",
            sessionDuration: "60 minutes",
        },
        healthNotes: "None.",
        remindersEnabled: true,
        staffNotes: ["Likes calming scents like lavender and chamomile."],
        messages: [],
        feedback: [
            { rating: 5, comment: "Best massage ever!", date: "2024-10-10" },
        ],
    },
    {
        id: 5,
        name: "James Miller",
        email: "cliente@example.com",
        lastAppointment: "2024-08-15 09:30",
        details: "Has multiple upcoming appointments.",
        avatar: "https://randomuser.me/api/portraits/men/30.jpg",
        tag: "Frequent",
        notes: "Loves strong pressure and long sessions.",
        appointmentHistory: [
            { date: "2025-02-12", type: "Deep Tissue", status: "Upcoming" },
            { date: "2025-02-20", type: "Hot Stone Massage", status: "Upcoming" },
            { date: "2025-02-25", type: "Thai Massage", status: "Upcoming" },
        ],
        preferences: {
            massageType: "Deep Tissue",
            pressureLevel: "Strong",
        },
        remindersEnabled: true,
        staffNotes: ["Avoid pressure on left shoulder due to injury."],
        messages: [],
        feedback: [
            { rating: 5, comment: "Excellent as always.", date: "2024-09-10" },
            { rating: 4, comment: "Would love stronger pressure next time.", date: "2024-10-12" },
        ],
    },
    {
        id: 6,
        name: "Lisa Ray",
        email: "clientf@example.com",
        lastAppointment: "2024-09-05 16:30",
        details: "Never left feedback.",
        avatar: "https://randomuser.me/api/portraits/women/34.jpg",
        tag: "New",
        notes: "Enjoys lighter pressure.",
        appointmentHistory: [
            { date: "2024-09-05", type: "Swedish Massage", status: "Completed" },
        ],
        preferences: {
            massageType: "Swedish Massage",
            pressureLevel: "Soft",
        },
        remindersEnabled: false,
        staffNotes: [],
        messages: [],
        feedback: [],
    },
    {
        id: 7,
        name: "David White",
        email: "clientg@example.com",
        lastAppointment: "2024-10-15 10:00",
        details: "Doesn't use reminders or messaging.",
        avatar: "https://randomuser.me/api/portraits/men/29.jpg",
        tag: "VIP",
        notes: "Prefers silent sessions, no small talk.",
        appointmentHistory: [
            { date: "2024-10-15", type: "Hot Stone Massage", status: "Completed" },
        ],
        preferences: {
            massageType: "Hot Stone Massage",
            pressureLevel: "Medium",
        },
        remindersEnabled: false,
        staffNotes: ["Client prefers minimal interaction during the session."],
        messages: [],
        feedback: [
            { rating: 5, comment: "Perfect session!", date: "2024-10-16" },
        ],
    },
    {
        id: 8,
        name: "Emily Johnson",
        email: "clienth@example.com",
        lastAppointment: "2025-01-10 14:00",
        details: "Loves hot stone therapy.",
        avatar: "https://randomuser.me/api/portraits/women/35.jpg",
        tag: "VIP",
        notes: "Prefers a quiet, relaxing environment.",
        appointmentHistory: [
            { date: "2024-12-20", type: "Hot Stone Massage", status: "Completed" },
            { date: "2025-01-10", type: "Hot Stone Massage", status: "Upcoming" },
        ],
        preferences: {
            massageType: "Hot Stone Massage",
            pressureLevel: "Soft",
        },
        remindersEnabled: true,
        staffNotes: ["Likes a silent, stress-free atmosphere."],
        messages: [],
        feedback: [
            { rating: 5, comment: "Absolutely fantastic!", date: "2024-12-21" },
            { rating: 5, comment: "Best experience every time!", date: "2025-01-01" },
        ],
    },
    {
        id: 9,
        name: "Henry Adams",
        email: "clienti@example.com",
        lastAppointment: "2024-10-05 11:00",
        details: "Unhappy with previous service.",
        avatar: "https://randomuser.me/api/portraits/men/28.jpg",
        tag: "Frequent",
        notes: "Had a bad experience, needs a follow-up discussion.",
        appointmentHistory: [
            { date: "2024-09-15", type: "Sports Massage", status: "Completed" },
            { date: "2024-10-05", type: "Swedish Massage", status: "Completed" },
        ],
        preferences: {
            massageType: "Swedish Massage",
            pressureLevel: "Soft",
        },
        remindersEnabled: false,
        staffNotes: ["Client was dissatisfied with the last service."],
        messages: [],
        feedback: [
            { rating: 1, comment: "Worst experience. Would not recommend.", date: "2024-10-06" },
            { rating: 2, comment: "Too much talking during the session.", date: "2024-09-16" },
        ],
    },
    {
        id: 10,
        name: "Olivia Spencer",
        email: "clientj@example.com",
        lastAppointment: "2019-08-20 16:00",
        details: "Used to be a regular but hasn't booked in years.",
        avatar: "https://randomuser.me/api/portraits/women/36.jpg",
        tag: "VIP",
        notes: "No recent activity, should be re-engaged.",
        appointmentHistory: [
            { date: "2018-11-15", type: "Aromatherapy", status: "Completed" },
            { date: "2019-08-20", type: "Swedish Massage", status: "Completed" },
        ],
        preferences: {
            massageType: "Swedish Massage",
            pressureLevel: "Medium",
        },
        remindersEnabled: false,
        staffNotes: ["Hasn't booked in 5+ years, might need an outreach."],
        messages: [],
        feedback: [],
    },
    {
        id: 11,
        name: "Daniel Kim",
        email: "clientk@example.com",
        lastAppointment: "2025-02-10 09:00",
        details: "Currently in session.",
        avatar: "https://randomuser.me/api/portraits/men/27.jpg",
        tag: "Frequent",
        notes: "Enjoys strong Thai Massage.",
        appointmentHistory: [
            { date: "2025-02-10", type: "Thai Massage", status: "Upcoming" },
        ],
        preferences: {
            massageType: "Thai Massage",
            pressureLevel: "Strong",
        },
        remindersEnabled: true,
        staffNotes: [],
        messages: [],
        feedback: [],
    },
    {
        id: 12,
        name: "Sophia Lee",
        email: "clientl@example.com",
        lastAppointment: "2025-01-10 14:00",
        details: "Loves trying different services.",
        avatar: "https://randomuser.me/api/portraits/women/37.jpg",
        tag: "Frequent",
        notes: "Schedules multiple appointments in a short period.",
        appointmentHistory: [
            { date: "2025-02-12", type: "Swedish Massage", status: "Upcoming" },
            { date: "2025-02-14", type: "Hot Stone Massage", status: "Upcoming" },
            { date: "2025-02-16", type: "Aromatherapy", status: "Upcoming" },
        ],
        preferences: {
            massageType: "Varied",
            pressureLevel: "Medium",
        },
        remindersEnabled: true,
        staffNotes: ["Client enjoys variety, asks for recommendations."],
        messages: [],
        feedback: [
            { rating: 4, comment: "Always a good experience.", date: "2024-12-30" },
        ],
    },
    {
        id: 13,
        name: "Andrew Scott",
        email: "clientm@example.com",
        lastAppointment: "2024-09-15 10:30",
        details: "Prefers no notifications.",
        avatar: "https://randomuser.me/api/portraits/men/26.jpg",
        tag: "New",
        notes: "Wants a massage, no extra engagement.",
        appointmentHistory: [
            { date: "2024-09-15", type: "Deep Tissue", status: "Completed" },
        ],
        preferences: {
            massageType: "Deep Tissue",
            pressureLevel: "Strong",
        },
        remindersEnabled: false,
        staffNotes: ["Does not want any follow-ups, prefers to book independently."],
        messages: [],
        feedback: [],
    },
    {
        id: 14,
        name: "Jessica Brown",
        email: "clientn@example.com",
        lastAppointment: "2025-01-15 11:00",
        details: "Leaves detailed feedback.",
        avatar: "https://randomuser.me/api/portraits/women/38.jpg",
        tag: "Frequent",
        notes: "Loves detailed massages, always leaves feedback.",
        appointmentHistory: [
            { date: "2025-01-15", type: "Hot Stone Massage", status: "Completed" },
        ],
        preferences: {
            massageType: "Hot Stone Massage",
            pressureLevel: "Soft",
        },
        remindersEnabled: true,
        staffNotes: ["Client prefers long, relaxing sessions."],
        messages: [
            { sender: "Client", content: "This was the most amazing session ever! I felt so relaxed afterward. Thank you for the effort!", timestamp: "2025-01-16 10:00 AM" },
        ],
        feedback: [
            { rating: 5, comment: "Incredible massage! I can't wait to come back.", date: "2025-01-16" },
        ],
    },
];


export const tagColors = {
    VIP: "bg-yellow-500",
    Frequent: "bg-green-500",
    New: "bg-blue-500",
};