import { Appointment } from "@features/appointments/types/appointments";

export const dummyAppointments: Appointment[] = [
    {
        id: 1,
        providerId: 1,
        clientId: 1,
        serviceType: "Massage",
        date: "2024-04-01",
        startTime: "08:30",
        endTime: "09:00",
        status: "Completed",
        notes: "Session completed successfully.",
        location: "Room 1",
        createdAt: "2024-03-31T10:00:00Z",
        updatedAt: "2024-04-01T09:00:00Z",
        metadata: {
            providerName: "Therapist A",
            clientName: "Client A",
        },
    },
    {
        id: 2,
        providerId: 2,
        clientId: 2,
        serviceType: "Massage",
        date: "2024-04-01",
        startTime: "09:45",
        endTime: "10:15",
        status: "Completed",
        notes: "Regular session.",
        location: "Room 2",
        createdAt: "2024-03-31T11:00:00Z",
        updatedAt: "2024-04-01T10:20:00Z",
        metadata: {
            providerName: "Therapist B",
            clientName: "Client B",
        },
    },
    {
        id: 3,
        providerId: 1,
        clientId: 3,
        serviceType: "Massage",
        date: "2024-04-01",
        startTime: "13:15",
        endTime: "14:15",
        status: "Cancelled",
        notes: "Cancelled session.",
        location: "Room 3",
        createdAt: "2024-03-31T12:00:00Z",
        updatedAt: "2024-04-01T12:50:00Z",
        metadata: {
            providerName: "Therapist A",
            clientName: "Client C",
        },
    },
    {
        id: 4,
        providerId: 3,
        clientId: 4,
        serviceType: "Massage",
        date: "2024-04-01",
        startTime: "14:30",
        endTime: "15:00",
        status: "Upcoming",
        notes: "Upcoming appointment.",
        location: "Room 2",
        createdAt: "2024-04-01T08:00:00Z",
        updatedAt: "2024-04-01T08:00:00Z",
        metadata: {
            providerName: "Therapist C",
            clientName: "Client D",
        },
    },
    {
        id: 5,
        providerId: 4,
        clientId: 5,
        serviceType: "Massage",
        date: "2024-04-01",
        startTime: "18:00",
        endTime: "19:00",
        status: "Upcoming",
        notes: "Follow-up session.",
        location: "Room 1",
        createdAt: "2024-04-01T09:00:00Z",
        updatedAt: "2024-04-01T09:00:00Z",
        metadata: {
            providerName: "Therapist D",
            clientName: "Client E",
        },
    },
    {
        id: 6,
        providerId: 2,
        clientId: 6,
        serviceType: "Massage",
        date: "2024-04-01",
        startTime: "19:15",
        endTime: "19:45",
        status: "Upcoming",
        notes: "Evening appointment.",
        location: "Room 3",
        createdAt: "2024-04-01T10:00:00Z",
        updatedAt: "2024-04-01T10:00:00Z",
        metadata: {
            providerName: "Therapist B",
            clientName: "Client F",
        },
    },
];

export const mockMessages = [
    {
        id: 1,
        sender: "Client A",
        content: "Thanks for the session!",
        timestamp: "2024-04-01T14:00:00Z",
    },
    {
        id: 2,
        sender: "Client B",
        content: "Can we reschedule?",
        timestamp: "2024-04-02T09:00:00Z",
    },
];

export const mockRevenueData = {
    weekly: [
        { x: "Mon", y: 300 },
        { x: "Tue", y: 450 },
        { x: "Wed", y: 500 },
        { x: "Thu", y: 600 },
        { x: "Fri", y: 700 },
    ],
    monthly: [
        { x: "Week 1", y: 3200 },
        { x: "Week 2", y: 4000 },
        { x: "Week 3", y: 3800 },
        { x: "Week 4", y: 4200 },
    ],
    yearly: [
        { x: "Jan", y: 12000 },
        { x: "Feb", y: 15000 },
        { x: "Mar", y: 17000 },
        { x: "Apr", y: 16000 },
        { x: "May", y: 18000 },
    ],
};
